
export const HIDE_TIME_PICKER = 'HIDE_TIME_PICKER';
export const SHOW_TIME_PICKER = 'SHOW_TIME_PICKER';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_DELETE_ITEM = 'SET_DELETE_ITEM';
export const REMOVE_DELETE_ITEM = 'REMOVE_DELETE_ITEM';
